#datasource
spring:
  datasource:
    url: jdbc:mysql:///user?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml       #加载resources下的所有mapper映射路径
  type-aliases-package: com.westworld.springbootmybatis.domain      #包扫描
#  config-location: 指定mybatis的核心配置文件
